### ISSUE TITLE
I can't test if it's not there.

### ISSUE THREAD

**Issue by Paradox75831004** [LouisSilva/LethalCompanyHarpGhost#1]
Why can't I summon this monster in the "LethalDevMode" test room or using "DanceTools"? I wanted to test compatibility and stuff in my build so that I could write a bug report in the future. How does this monster work? Why is it not in the database?

![image](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/72872478/52c47387-c602-4175-a551-8b2b7c3fc1be)
![image](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/72872478/b5677a7b-82b9-4f4f-8f28-4c8949f8b506)
![image](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/72872478/4f90de69-f807-463f-b3d1-6cc1a1063737)
![image](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/72872478/699bd175-fd11-4c99-82a5-f77c26e4529a)
![image](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/72872478/b75f81ea-273d-4d25-aa1e-eff9b5e4e767)

**Comment by Paradox75831004** [comment]
I'm sorry, I found it in another LethalDev tab.
![image](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/72872478/c0da0167-3280-459c-9113-e924a2c1e1ba)

**Comment by Paradox75831004** [comment]
He's not hunting, what's wrong with him? How should it work?...
![image](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/72872478/4785857b-b287-4fa6-8120-a8c1fb57237d)

**Comment by Paradox75831004** [comment]
018db74d-6757-54FD-3924-2E6763742585 - Our assembly

**Comment by LouisSilva** [comment]
> I'm sorry, I found it in another LethalDev tab. ![image](https://private-user-images.githubusercontent.com/72872478/305646798-c0da0167-3280-459c-9113-e924a2c1e1ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTU5NDIsIm5iZiI6MTcwODE5NTY0MiwicGF0aCI6Ii83Mjg3MjQ3OC8zMDU2NDY3OTgtYzBkYTAxNjctMzI4MC00NTljLTkxMTMtZTkyNGEyYzFlMWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE4NDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhN2I4ZmM0OWQwMjc4MmU5MWRmNjVjZDhlMzhhZDEwYTRhZGI0NWU1MmZkNmE2ZmMyODJjZTBjYjA3MjJmYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vaYnXflWvjFUlFJc4YLfPQ8e3b7DcvG53FGG6kp98VQ)

The enemy is registered/added to the game using LethalLib. With DanceTools it should work, but I am using my own version of it to be fair. Lethal Dev might work but for some reason whenever I tried it it never worked.

**Comment by LouisSilva** [comment]
> He's not hunting, what's wrong with him? How should it work?... ![image](https://private-user-images.githubusercontent.com/72872478/305646951-4785857b-b287-4fa6-8120-a8c1fb57237d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTU5NDIsIm5iZiI6MTcwODE5NTY0MiwicGF0aCI6Ii83Mjg3MjQ3OC8zMDU2NDY5NTEtNDc4NTg1N2ItYjI4Ny00ZmE2LTgxMjAtYThjMWZiNTcyMzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE4NDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZTA3MDJhMmE2MzU0N2JjZWM4MTQzMWYwZjcxMGI2ZTZiZTE5NDk5YmE4YzRlMmI1NzA0MzhlNGI3ODFmN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dmL45yZVkOv9DP0_1y_UkkLPs1Iqh3e6j872lNE2Y94)

Its not working because your not inside the facility. I am going to fix it because it should be a small fix but I haven't done it **yet** because it doesn't spawn outside. The LethalDevMode test room is also technically outside (i think) so it won't work there either.
