### ISSUE TITLE
Hey are you on the main modding discord?

### ISSUE THREAD

**Issue by ImpulsiveLad** [LouisSilva/LethalCompanyHarpGhost#2]
I don't see the thread for your mod, is it just called harp something?

**Comment by ImpulsiveLad** [comment]
I imagine the in code name would be HarpGhost for lethallethalloader customization?

**Comment by LouisSilva** [comment]
> I imagine the in code name would be HarpGhost for lethallethalloader customization?

Yea in the code its called HarpGhost, the "Haunted Harpist" name is only used in the scan node and bestiary stuff

**Comment by LouisSilva** [comment]
> I don't see the thread for your mod, is it just called harp something?

I am going to add it, but after its out of beta because I'd prefer if people used it when the little things I mentioned in the readme are done.

**Comment by ImpulsiveLad** [comment]
ic I'm just trying to understand how it works, I now get you can't grab it out of their hand but am not sure what to do instead, violence?

**Comment by LouisSilva** [comment]
> ic I'm just trying to understand how it works, I now get you can't grab it out of their hand but am not sure what to do instead, violence?

He drops it when you've angered him, which can be achieved by doing one or more of the following:

- Making too much noise arround him
- Attacking him
- Stunning him
