### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ImpulsiveLad** [LouisSilva/LethalCompanyHarpGhost#3]
https://streamable.com/47cwyn
Am I supposed to be able to grab it or does it not work? sorry if I just don't understand the mod

**Comment by LouisSilva** [comment]
You can't grab the harp while the ghost is holding it, like the nutcracker's shotgun. If you go up to the nutcracker it will say "grab item" but you can't anyway. You can only get the harp through annoying the ghost by making too much noise/attacking it/stunning it.
