### ISSUE TITLE
Ghost doesn't spawn.

### ISSUE THREAD

**Issue by Qugar** [LouisSilva/LethalCompanyHarpGhost#5]
Unfortunately, the ghost does not spawn and is not recognized by AdvancedCompany.

**Comment by LouisSilva** [comment]
With the new update its fixed, I'll leave the issue up for a couple days just incase it still doesn't work

**Comment by Qugar** [comment]
Yes, the ghost spawns now, but it only seems to spawn properly on vanilla moons.

He spawned on a modded moon without a harp and slid around on his back.

![grafik](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/8191849/5db843de-1e5b-48cf-9419-6e55072d31e6)

Also, the harps don't spawn. It shows me that some have spawned in the level, but they don't really exist. To test it, I increased the spawn rate, except for harps, 3 other items spawned. I could find these , but absolutely no harp. Happened on vanilla and modded moons.

While I was carrying a harp from a killed ghost, my character broke his hand due to the weight of the harp. Please make the harp a little lighter. :joy:

![grafik](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/8191849/6e096139-58eb-46dd-a262-1d0831abb5b9)

**Comment by LouisSilva** [comment]
What modded moon did you use? As for the disappearing harps, theres a bug where if a harp is spawned through other means than the ghost spawning it, then it will just completely glitch out. Also the harp is supposed to be two handed, and because the item offsets are different between a player holding the harp and an enemy, it sometimes bugs out and doesn't change the offets.

Thanks for reporting the bugs, I'll get them fixed :)

**Comment by Qugar** [comment]
I tested it on the modded moons Auralis and Triskelion.
[https://thunderstore.io/c/lethal-company/p/AudioKnight/StarlancerMoons/](url)

With the interior Dantors Mental Hospital.
[https://thunderstore.io/c/lethal-company/p/Dantor/Dantors_Mental_Hospital/](url)

If you want, I can also test other modded moons with other interiors.

As for the bug that the harp bugs in the player's hands. Wouldn't it be possible to delete the enemy's harp and then spawn a new object. Practically a harp for enemies and one as loot. I'm sorry if my thought is completely wrong, I'm just trying to help.

And thank you for your work, I find the enemy really interesting.

**Comment by LouisSilva** [comment]
I've tried a few times to reproduce the sliding ghost bug, can't get it to work but I'll keep on trying. The player hands thing I think I've fixed anyway, I'll upload the fixed version soon.

Thank you for the kind words :)

**Comment by LouisSilva** [comment]
Actually I managed to reproduce it, it happens when you kill a ghost for some reason all other ghosts do the death animation, for some reason they are all linked in a way, ill get it fixed.

**Comment by Qugar** [comment]
It could be that FairAI killed a ghost through mines on both maps, which would be unfortunate but not impossible. :joy:

**Comment by Qugar** [comment]
Looks like everything is working now.

Very good job, thank you.
