### ISSUE TITLE
[V50] [Error  : Unity Log] MissingFieldException: Field not found: int .EnemyType.PowerLevel Due to: Could not find field in class

### ISSUE THREAD

**Issue by CoolLKKPS** [LouisSilva/LethalCompanyHarpGhost#6]
[Error  : Unity Log] MissingFieldException: Field not found: int .EnemyType.PowerLevel Due to: Could not find field in class
Stack trace:
LethalCompanyHarpGhost.HarpGhostPlugin.Awake () (at C:/Users/Louis/RiderProjects/LethalCompanyHarpGhost/LethalCompanyHarpGhost/src/Plugin.cs:77)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[Error  : Unity Log] MissingFieldException: Field not found: int .EnemyType.PowerLevel Due to: Could not find field in class
Stack trace:
LethalCompanyHarpGhost.HarpGhostPlugin.Awake () (at C:/Users/Louis/RiderProjects/LethalCompanyHarpGhost/LethalCompanyHarpGhost/src/Plugin.cs:77)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by CoolLKKPS** [comment]
in my opinion, this cause by LethalLib

**Comment by Nekoaii** [comment]
LethalLib has been updated and im still getting the same Error

**Comment by LouisSilva** [comment]
Sorry I only just saw this. I haven't updated it to v50 yet, but I will in the next couple days

**Comment by NighteyezWolf** [comment]
Im on V49 and got the same error. Sadly they do no spawn.

**Comment by LouisSilva** [comment]
Try version 1.3.7+, the bug should be fixed

> Im on V49 and got the same error. Sadly they do no spawn.
