### ISSUE TITLE
[v50] [Error] Haunted Harpist unable to kill players

### ISSUE THREAD

**Issue by EpicIsGabe** [LouisSilva/LethalCompanyHarpGhost#8]
![image](https://github.com/LouisSilva/LethalCompanyHarpGhost/assets/166662406/d3d905d6-fd4f-4317-8609-2be26ae8c7a9)

Error attached when Harpist tries to kill player

**Comment by LouisSilva** [comment]
> Thank you <3 -Gabriel ThompsonOn Apr 10, 2024, at 8:26 PM, Louis ***@***.***> wrote:﻿ That error is made by the FreddyKrueger enemy. The Freddy enemy has a function that is called everytime a player is damaged, and something in their code makes it give an error. The Harpist is mentioned in the stack trace because thats what started that function to be called. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Np :)
